version: "2"
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  server:
    build:
      context: ./Server
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - MONGO_URL=mongodb://mongo/politicalcapital
      - APP_PORT=3001
    volumes:
      - ./Server:/server_docker
    ports:
      - "3001:3001"
    links:
      - mongo
  interface:
    build:
      context: ./Interface
      dockerfile: Dockerfile
    volumes:
      - ./Interface:/usr/src/app
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_POLITICAL_CAPITAL=server:3001
      - REACT_APP_DEBUG=true
    links:
      - server