version: "2"
services:
  mongodb:
    container_name: political_capital_database
    image: mongo:latest
    ports:
      - "27017:27017"
  server:
    container_name: political_capital_server
    build:
      context: ./Server
      dockerfile: Dockerfile
    environment:
      - ENV CODECLIMATE_REPO_TOKEN=112bcc20ceaa82677c01e9147e3f51430425778ba961e1f109f4ef1d413c9cec
      - ENV APP_PORT=80
      - ENV REACT_APP_DEBUG=true
      - ENV NODE_ENV=development
    volumes:
      - ./Server/Routes:/server_docker/Routes
      - ./Server/config:/server_docker/config
    ports:
      - "80:80"
    links:
      - mongodb
    depends_on:
      - mongodb
  interface:
    container_name: political_capital_interface
    volumes:
      - ./Interface/src:/interface_docker/src
    restart: always
    build:
      context: ./Interface
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "35729:35729"
    environment:
      - REACT_APP_POLITICAL_CAPITAL=server:3001
      - REACT_APP_DEBUG=true
    links:
      - server